import csv
from pathlib import Path

STATIONS = [
    # Indian Polar Research Stations
    {
        'station_id': 'IND-STN-01',
        'station_name': 'Dakshin Gangotri',
        'country': 'India',
        'operator': 'NCPOR / Ministry of Earth Sciences',
        'latitude': '70° 45\' 12" S',
        'longitude': '11° 38\' 13" E',
        'latitude_decimal': -70.7533,
        'longitude_decimal': 11.6370,
        'elevation_m': 130.0,
        'location': 'Ice shelf, Princess Astrid Coast, Queen Maud Land, East Antarctica',
        'establishment_year': 1983,
        'status': 'Historical',
        'research_activities': 'Atmospheric sciences, Meteorology, Glaciology, Geomagnetism, Earth Sciences, Biology',
        'source_url': 'https://npdc.ncpor.res.in/npdc/surfacedata_gangotri_maitri.jsp'
    },
    {
        'station_id': 'IND-STN-02',
        'station_name': 'Maitri',
        'country': 'India',
        'operator': 'NCPOR / Ministry of Earth Sciences',
        'latitude': '70° 45\' 52" S',
        'longitude': '11° 44\' 03" E',
        'latitude_decimal': -70.7644,
        'longitude_decimal': 11.7342,
        'elevation_m': 130.0,
        'location': 'Schirmacher Oasis, Central Dronning Maud Land, East Antarctica',
        'establishment_year': 1988,
        'status': 'Active - Year Round',
        'research_activities': 'Atmospheric sciences, Meteorology, Geomagnetism, Seismology, Glaciology, Environmental Sciences',
        'source_url': 'https://npdc.ncpor.res.in/npdc/research-stations.action'
    },
    {
        'station_id': 'IND-STN-03',
        'station_name': 'Bharati',
        'country': 'India',
        'operator': 'NCPOR / Ministry of Earth Sciences',
        'latitude': '69° 24.41\' S',
        'longitude': '76° 11.72\' E',
        'latitude_decimal': -69.4068,
        'longitude_decimal': 76.1953,
        'elevation_m': 35.0,
        'location': 'Between Thala Fjord & Quilty Bay, Larsemann Hills, East Antarctica',
        'establishment_year': 2012,
        'status': 'Active - Year Round',
        'research_activities': 'Atmospheric physics, Oceanography, Geology, Glaciology, Paleoclimatology, Satellite remote sensing',
        'source_url': 'https://npdc.ncpor.res.in/npdc/research-stations.action'
    },
    {
        'station_id': 'IND-STN-04',
        'station_name': 'India Bay Camp',
        'country': 'India',
        'operator': 'NCPOR / Indian Navy / MoES',
        'latitude': '69° 59\' 00" S',
        'longitude': '11° 55\' 00" E',
        'latitude_decimal': -69.9833,
        'longitude_decimal': 11.9167,
        'elevation_m': 20.0,
        'location': 'Princess Astrid Coast ice shelf edge, Dronning Maud Land, East Antarctica',
        'establishment_year': 1981,
        'status': 'Summer Only',
        'research_activities': 'Logistics staging, Sea ice monitoring, Coastal oceanography, Cargo offloading',
        'source_url': 'https://npdc.ncpor.res.in/npdc/antarctica_home.action'
    },
    # Premier International Antarctic Scientific Research Stations
    {
        'station_id': 'USA-STN-01',
        'station_name': 'McMurdo Station',
        'country': 'United States',
        'operator': 'National Science Foundation (USAP)',
        'latitude': '77° 50\' 47" S',
        'longitude': '166° 40\' 06" E',
        'latitude_decimal': -77.8464,
        'longitude_decimal': 166.6683,
        'elevation_m': 24.0,
        'location': 'Ross Island, McMurdo Sound',
        'establishment_year': 1956,
        'status': 'Active - Year Round',
        'research_activities': 'Astrophysics, Biology, Geophysics, Glaciology, Ocean ecosystems',
        'source_url': 'https://www.nsf.gov/geo/opp/antarct/mcmurdo.jsp'
    },
    {
        'station_id': 'USA-STN-02',
        'station_name': 'Amundsen-Scott South Pole Station',
        'country': 'United States',
        'operator': 'National Science Foundation (USAP)',
        'latitude': '90° 00\' 00" S',
        'longitude': '0° 00\' 00" E',
        'latitude_decimal': -90.0000,
        'longitude_decimal': 0.0000,
        'elevation_m': 2835.0,
        'location': 'Geographic South Pole, Polar Plateau',
        'establishment_year': 1956,
        'status': 'Active - Year Round',
        'research_activities': 'Astrophysics (IceCube, South Pole Telescope), Atmospheric chemistry, Climatology',
        'source_url': 'https://www.nsf.gov/geo/opp/antarct/southpole.jsp'
    },
    {
        'station_id': 'USA-STN-03',
        'station_name': 'Palmer Station',
        'country': 'United States',
        'operator': 'National Science Foundation (USAP)',
        'latitude': '64° 46\' 27" S',
        'longitude': '64° 03\' 11" W',
        'latitude_decimal': -64.7742,
        'longitude_decimal': -64.0531,
        'elevation_m': 10.0,
        'location': 'Anvers Island, Antarctic Peninsula',
        'establishment_year': 1968,
        'status': 'Active - Year Round',
        'research_activities': 'Marine biology, Pelagic ecosystems, Oceanography, Glaciology',
        'source_url': 'https://www.nsf.gov/geo/opp/antarct/palmer.jsp'
    },
    {
        'station_id': 'GBR-STN-01',
        'station_name': 'Rothera Research Station',
        'country': 'United Kingdom',
        'operator': 'British Antarctic Survey (BAS)',
        'latitude': '67° 34\' 08" S',
        'longitude': '68° 07\' 29" W',
        'latitude_decimal': -67.5689,
        'longitude_decimal': -68.1247,
        'elevation_m': 16.0,
        'location': 'Adelaide Island, Antarctic Peninsula',
        'establishment_year': 1975,
        'status': 'Active - Year Round',
        'research_activities': 'Meteorology, Glaciology, Marine biology, Aviation logistics hub',
        'source_url': 'https://www.bas.ac.uk/polar-operations/sites-and-facilities/facility/rothera/'
    },
    {
        'station_id': 'GBR-STN-02',
        'station_name': 'Halley VI Research Station',
        'country': 'United Kingdom',
        'operator': 'British Antarctic Survey (BAS)',
        'latitude': '75° 34\' 59" S',
        'longitude': '25° 30\' 00" W',
        'latitude_decimal': -75.5831,
        'longitude_decimal': -25.5000,
        'elevation_m': 30.0,
        'location': 'Brunt Ice Shelf, Coats Land',
        'establishment_year': 1956,
        'status': 'Summer Only',
        'research_activities': 'Atmospheric physics, Space weather, Ozone hole monitoring (Dobson site)',
        'source_url': 'https://www.bas.ac.uk/polar-operations/sites-and-facilities/facility/halley/'
    },
    {
        'station_id': 'RUS-STN-01',
        'station_name': 'Vostok Station',
        'country': 'Russia',
        'operator': 'Arctic and Antarctic Research Institute (AARI)',
        'latitude': '78° 27\' 52" S',
        'longitude': '106° 50\' 14" E',
        'latitude_decimal': -78.4644,
        'longitude_decimal': 106.8372,
        'elevation_m': 3488.0,
        'location': 'Inland Polar Plateau, Lake Vostok region',
        'establishment_year': 1957,
        'status': 'Active - Year Round',
        'research_activities': 'Deep ice core paleoclimatology, Subglacial Lake Vostok exploration, Magnetometry',
        'source_url': 'http://www.aari.ru'
    },
    {
        'station_id': 'RUS-STN-02',
        'station_name': 'Mirny Station',
        'country': 'Russia',
        'operator': 'Arctic and Antarctic Research Institute (AARI)',
        'latitude': '66° 33\' 07" S',
        'longitude': '93° 00\' 53" E',
        'latitude_decimal': -66.5519,
        'longitude_decimal': 93.0147,
        'elevation_m': 35.0,
        'location': 'Davis Sea coast, Queen Mary Land',
        'establishment_year': 1956,
        'status': 'Active - Year Round',
        'research_activities': 'Meteorology, Glaciology, Seismology, Coastal oceanography',
        'source_url': 'http://www.aari.ru'
    },
    {
        'station_id': 'AUS-STN-01',
        'station_name': 'Casey Station',
        'country': 'Australia',
        'operator': 'Australian Antarctic Division (AAD)',
        'latitude': '66° 16\' 55" S',
        'longitude': '110° 31\' 32" E',
        'latitude_decimal': -66.2819,
        'longitude_decimal': 110.5256,
        'elevation_m': 32.0,
        'location': 'Vincennes Bay, Wilkes Land',
        'establishment_year': 1969,
        'status': 'Active - Year Round',
        'research_activities': 'Law Dome ice coring, Space physics, Moss bed terrestrial biology',
        'source_url': 'https://www.antarctica.gov.au/about-antarctica/stations/casey/'
    },
    {
        'station_id': 'AUS-STN-02',
        'station_name': 'Davis Station',
        'country': 'Australia',
        'operator': 'Australian Antarctic Division (AAD)',
        'latitude': '68° 34\' 36" S',
        'longitude': '77° 58\' 03" E',
        'latitude_decimal': -68.5767,
        'longitude_decimal': 77.9675,
        'elevation_m': 18.0,
        'location': 'Vestfold Hills, Princess Elizabeth Land',
        'establishment_year': 1957,
        'status': 'Active - Year Round',
        'research_activities': 'Atmospheric LiDAR, Sea ice dynamics, Southern Ocean ecosystems',
        'source_url': 'https://www.antarctica.gov.au/about-antarctica/stations/davis/'
    },
    {
        'station_id': 'AUS-STN-03',
        'station_name': 'Mawson Station',
        'country': 'Australia',
        'operator': 'Australian Antarctic Division (AAD)',
        'latitude': '67° 36\' 10" S',
        'longitude': '62° 52\' 26" E',
        'latitude_decimal': -67.6028,
        'longitude_decimal': 62.8739,
        'elevation_m': 16.0,
        'location': 'Holme Bay, Mac. Robertson Land',
        'establishment_year': 1954,
        'status': 'Active - Year Round',
        'research_activities': 'Cosmic ray observatory, Adelie & Emperor penguin census, Geomagnetism',
        'source_url': 'https://www.antarctica.gov.au/about-antarctica/stations/mawson/'
    },
    {
        'station_id': 'DEU-STN-01',
        'station_name': 'Neumayer Station III',
        'country': 'Germany',
        'operator': 'Alfred Wegener Institute (AWI)',
        'latitude': '70° 40\' 26" S',
        'longitude': '8° 16\' 00" W',
        'latitude_decimal': -70.6739,
        'longitude_decimal': -8.2667,
        'elevation_m': 40.0,
        'location': 'Ekström Ice Shelf, Atka Bay',
        'establishment_year': 2009,
        'status': 'Active - Year Round',
        'research_activities': 'Geophysics, Meteorology, Air chemistry, EDEN ISS greenhouse research',
        'source_url': 'https://www.awi.de/en/expedition/stations/neumayer-station-iii.html'
    },
    {
        'station_id': 'FRA-ITA-01',
        'station_name': 'Concordia Station',
        'country': 'France / Italy',
        'operator': 'IPEV (France) / PNRA (Italy)',
        'latitude': '75° 06\' 00" S',
        'longitude': '123° 20\' 00" E',
        'latitude_decimal': -75.1000,
        'longitude_decimal': 123.3333,
        'elevation_m': 3233.0,
        'location': 'Dome C, East Antarctic Plateau',
        'establishment_year': 2005,
        'status': 'Active - Year Round',
        'research_activities': 'Astronomy, EPICA deep ice coring, Human spaceflight isolation analogue (ESA)',
        'source_url': 'https://www.institut-polaire.fr'
    },
    {
        'station_id': 'JPN-STN-01',
        'station_name': 'Showa Station (Syowa)',
        'country': 'Japan',
        'operator': 'National Institute of Polar Research (NIPR)',
        'latitude': '69° 00\' 25" S',
        'longitude': '39° 35\' 01" E',
        'latitude_decimal': -69.0069,
        'longitude_decimal': 39.5836,
        'elevation_m': 29.0,
        'location': 'East Ongul Island, Queen Maud Land',
        'establishment_year': 1957,
        'status': 'Active - Year Round',
        'research_activities': 'Upper atmospheric physics, Auroral observations, Seismology, Meteorology',
        'source_url': 'https://www.nipr.ac.jp/english/'
    },
    {
        'station_id': 'CHN-STN-01',
        'station_name': 'Zhongshan Station',
        'country': 'China',
        'operator': 'Polar Research Institute of China (PRIC)',
        'latitude': '69° 22\' 24" S',
        'longitude': '76° 22\' 40" E',
        'latitude_decimal': -69.3733,
        'longitude_decimal': 76.3778,
        'elevation_m': 15.0,
        'location': 'Larsemann Hills, Princess Elizabeth Land',
        'establishment_year': 1989,
        'status': 'Active - Year Round',
        'research_activities': 'Marine geology, Geomagnetism, Glaciology, Inland traverse staging',
        'source_url': 'http://www.pric.org.cn'
    },
    {
        'station_id': 'NOR-STN-01',
        'station_name': 'Troll Research Station',
        'country': 'Norway',
        'operator': 'Norwegian Polar Institute (NPI)',
        'latitude': '72° 00\' 43" S',
        'longitude': '2° 31\' 56" E',
        'latitude_decimal': -72.0119,
        'longitude_decimal': 2.5322,
        'elevation_m': 1275.0,
        'location': 'Jutulsessen nunatak, Queen Maud Land',
        'establishment_year': 1990,
        'status': 'Active - Year Round',
        'research_activities': 'Atmospheric monitoring, Satellite data reception (KSAT), Glaciology',
        'source_url': 'https://www.npolar.no/en/troll/'
    },
    {
        'station_id': 'ARG-STN-01',
        'station_name': 'Esperanza Base',
        'country': 'Argentina',
        'operator': 'Dirección Nacional del Antártico (DNA)',
        'latitude': '63° 23\' 42" S',
        'longitude': '56° 59\' 46" W',
        'latitude_decimal': -63.3950,
        'longitude_decimal': -56.9961,
        'elevation_m': 25.0,
        'location': 'Hope Bay, Trinity Peninsula',
        'establishment_year': 1952,
        'status': 'Active - Year Round',
        'research_activities': 'Glaciology, Seismology, Oceanography, Ornithology (Adélie penguin colony)',
        'source_url': 'https://www.dna.gob.ar'
    }
]

target_file = Path('combined_raw/stations.csv')
fieldnames = [
    'station_id', 'station_name', 'country', 'operator',
    'latitude', 'longitude', 'latitude_decimal', 'longitude_decimal',
    'elevation_m', 'location', 'establishment_year', 'status',
    'research_activities', 'source_url'
]

with open(target_file, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(STATIONS)

print(f"Successfully wrote {len(STATIONS)} Antarctic stations to {target_file}")
